apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.0.19
  values:
    controller:
      resources:
        requests:
          cpu: 50m
      replicaCount: 2

