apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 16.8.5
  values:
    auth:
      enabled: true
    master:
      resources:
        limits:
          memory: 50Mi
          cpu: 50m
    replica:
      replicaCount: 1
      resources:
        limits:
          memory: 50Mi
          cpu: 50m
