apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage
namePrefix: stage-
bases:
- ../base/
patchesStrategicMerge:
- redis.yaml
- nginx.yaml
- app.yaml

#transformers:
#- |-
#  apiVersion: builtin
#  kind: PrefixSuffixTransformer
#  metadata:
#    name: releaseNameprefixer
#  prefix: stage-
#  fieldSpecs:
#  - path: spec/releaseName

